# Generated by Django 4.0.1 on 2022-04-09 05:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('number', models.PositiveIntegerField()),
                ('password', models.CharField(default='', max_length=15)),
                ('confirmPassword', models.CharField(default='', max_length=15)),
                ('address', models.CharField(default='', max_length=150)),
                ('link', models.CharField(default='', max_length=55)),
                ('payment_due_date', models.DateField(default=datetime.datetime(2022, 4, 24, 5, 10, 28, 55408))),
                ('created_by', models.CharField(default=0, max_length=100)),
                ('totalNoOfReferrals', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PrsignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('number', models.PositiveIntegerField()),
                ('password', models.CharField(default='', max_length=15)),
                ('confirmPassword', models.CharField(default='', max_length=15)),
                ('link', models.CharField(default='', max_length=55)),
                ('recommend_by', models.CharField(default='', max_length=30)),
                ('payment_due_date', models.DateField(default=datetime.datetime(2022, 4, 24, 5, 10, 28, 55067))),
                ('ispaid', models.BooleanField(default=False)),
                ('isGivenBySir', models.BooleanField(default=False)),
                ('isPaymentRecievedFromSir', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Offerings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalAmount', models.CharField(default=0, max_length=15)),
                ('monthlyAmount', models.CharField(default=0, max_length=15)),
                ('pendingAmount', models.CharField(default=0, max_length=15)),
                ('isPaymentRecieved', models.BooleanField(default=False)),
                ('paymentRecievedDate', models.DateTimeField(blank=True, default=None, null=True)),
                ('joiningDate', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('tierName', models.CharField(default=0, max_length=15)),
                ('tierNo', models.PositiveIntegerField(default=0)),
                ('percentage', models.PositiveIntegerField(default=0)),
                ('updatedTierNo', models.PositiveIntegerField(default=0)),
                ('isTierCompleted', models.BooleanField(default=False)),
                ('CA', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CA.casignup')),
            ],
        ),
    ]
