# Generated by Django 4.0.1 on 2022-04-06 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casignup',
            name='subuser',
        ),
        migrations.AlterField(
            model_name='casignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 21, 10, 48, 49, 587392)),
        ),
        migrations.AlterField(
            model_name='offerings',
            name='payment_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='prsignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 21, 10, 48, 49, 587080)),
        ),
    ]
