# Generated by Django 4.0.1 on 2022-04-09 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0007_alter_casignup_payment_due_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prsignup',
            old_name='isGivenBySir',
            new_name='isAmountCalculated',
        ),
        migrations.RemoveField(
            model_name='prsignup',
            name='isPaymentRecievedFromSir',
        ),
        migrations.AddField(
            model_name='offerings',
            name='isGivenBySir',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='casignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 24, 9, 47, 46, 64126)),
        ),
        migrations.AlterField(
            model_name='prsignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 24, 9, 47, 46, 63800)),
        ),
    ]
