# Generated by Django 4.0.1 on 2022-04-07 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0008_alter_casignup_payment_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casignup',
            name='address',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='casignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 22, 4, 57, 45, 547947)),
        ),
        migrations.AlterField(
            model_name='offerings',
            name='joiningDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 7, 4, 57, 45, 548342), null=True),
        ),
        migrations.AlterField(
            model_name='prsignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 22, 4, 57, 45, 547624)),
        ),
    ]
