# Generated by Django 4.0.1 on 2022-04-09 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0008_rename_isgivenbysir_prsignup_isamountcalculated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 24, 9, 47, 51, 123243)),
        ),
        migrations.AlterField(
            model_name='prsignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 24, 9, 47, 51, 122913)),
        ),
    ]
