# Generated by Django 4.0.1 on 2022-04-08 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0012_alter_casignup_payment_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerings',
            name='isTierCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='casignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 23, 5, 56, 5, 369092)),
        ),
        migrations.AlterField(
            model_name='prsignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 23, 5, 56, 5, 368739)),
        ),
    ]
