# Generated by Django 4.0.1 on 2022-04-09 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0014_remove_offerings_totalamount_casignup_totalamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 24, 11, 1, 15, 172061)),
        ),
        migrations.AlterField(
            model_name='prsignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 24, 11, 1, 15, 171723)),
        ),
    ]
