# Generated by Django 4.0.1 on 2022-04-08 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0014_alter_casignup_payment_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerings',
            name='updatedTierNo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='casignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 23, 6, 33, 11, 337474)),
        ),
        migrations.AlterField(
            model_name='prsignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 23, 6, 33, 11, 337142)),
        ),
    ]
