# Generated by Django 4.0.1 on 2022-04-11 04:18

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0015_alter_casignup_payment_due_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerings',
            old_name='isGivenBySir',
            new_name='isPaymentGivenBySir',
        ),
        migrations.RemoveField(
            model_name='offerings',
            name='joiningDate',
        ),
        migrations.RemoveField(
            model_name='offerings',
            name='updatedTierNo',
        ),
        migrations.AddField(
            model_name='casignup',
            name='joiningDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='casignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 26, 4, 18, 28, 382190)),
        ),
        migrations.AlterField(
            model_name='prsignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 26, 4, 18, 28, 381859)),
        ),
    ]
