# Generated by Django 4.0.1 on 2022-04-11 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0016_rename_isgivenbysir_offerings_ispaymentgivenbysir_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 26, 4, 18, 41, 464141)),
        ),
        migrations.AlterField(
            model_name='prsignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 26, 4, 18, 41, 463816)),
        ),
    ]
