# Generated by Django 4.0.1 on 2022-04-11 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0017_alter_casignup_payment_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerings',
            name='pendingAmount',
        ),
        migrations.AddField(
            model_name='casignup',
            name='pendingAmount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='casignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 26, 6, 55, 46, 106567)),
        ),
        migrations.AlterField(
            model_name='prsignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 26, 6, 55, 46, 106224)),
        ),
    ]
