# Generated by Django 4.0.3 on 2022-06-15 05:09

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0019_alter_casignup_payment_due_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerings',
            old_name='isTierCompleted',
            new_name='isMonthCompleted',
        ),
        migrations.RemoveField(
            model_name='offerings',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='offerings',
            name='tierName',
        ),
        migrations.RemoveField(
            model_name='offerings',
            name='tierNo',
        ),
        migrations.RemoveField(
            model_name='prsignup',
            name='isAmountCalculated',
        ),
        migrations.AddField(
            model_name='casignup',
            name='percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offerings',
            name='objectCreatedDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='prsignup',
            name='joiningDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='prsignup',
            name='totalNoOfReferrals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='casignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 30, 5, 9, 18, 298777)),
        ),
        migrations.AlterField(
            model_name='prsignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 30, 5, 9, 18, 298432)),
        ),
    ]
