# Generated by Django 4.0.3 on 2022-06-15 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0020_rename_istiercompleted_offerings_ismonthcompleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerings',
            name='CA',
        ),
        migrations.RenameField(
            model_name='prsignup',
            old_name='link',
            new_name='ref_code',
        ),
        migrations.RemoveField(
            model_name='prsignup',
            name='confirmPassword',
        ),
        migrations.AlterField(
            model_name='prsignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 30, 5, 43, 52, 941520)),
        ),
        migrations.DeleteModel(
            name='CasignUp',
        ),
        migrations.DeleteModel(
            name='Offerings',
        ),
    ]
