# Generated by Django 4.0.3 on 2022-06-15 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0021_remove_offerings_ca_rename_link_prsignup_ref_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prsignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 30, 5, 44, 2, 78281)),
        ),
    ]
