# Generated by Django 4.0.3 on 2022-06-15 07:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0024_remove_prsignup_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prsignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 30, 7, 24, 41, 631452)),
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('comp_start_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('comp_due_date', models.DateField(default=datetime.datetime(2022, 6, 30, 7, 24, 41, 631768))),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CA.prsignup')),
            ],
        ),
    ]
