# Generated by Django 4.0.1 on 2022-04-04 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0030_casignup_subuser_alter_casignup_payment_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casignup',
            name='amount',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='casignup',
            name='percentage',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='casignup',
            name='totalNoOfReferrals',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='casignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 19, 9, 40, 17, 571678)),
        ),
        migrations.AlterField(
            model_name='prsignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 19, 9, 40, 17, 571372)),
        ),
    ]
