# Generated by Django 4.0.1 on 2022-04-04 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0031_casignup_amount_casignup_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prsignup',
            name='ispaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='casignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 19, 11, 5, 18, 915275)),
        ),
        migrations.AlterField(
            model_name='prsignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 19, 11, 5, 18, 914952)),
        ),
    ]
